# Generated by Django 3.2.13 on 2024-12-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gontobbo_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
